import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {esc,pages,site,routeFile,renderPage,townIndex,build} from '../scripts/build.mjs';
test('mantiene mayúsculas, carpetas y .html',()=>{assert.equal(routeFile('/Antenas-Burgos/lerma.html'),'Antenas-Burgos/lerma.html');assert.equal(routeFile('/Antenas-Bizkaia/'),'Antenas-Bizkaia/index.html');assert.equal(routeFile('/'),'index.html');});
test('rechaza rutas fuera del proyecto',()=>{for(const p of ['/../secret','/a?b','/a\\b'])assert.throws(()=>routeFile(p));});
test('escapa texto y atributos',()=>assert.equal(esc('<a "x"> &'), '&lt;a &quot;x&quot;&gt; &amp;'));
test('trece páginas base separadas sin importar otras localidades',()=>{assert.equal(pages.length,13);assert.equal(pages.filter(p=>p.type==='province').length,10);assert.equal(pages.filter(p=>p.type==='town').length,2);});
test('preview noindex sin analítica en todas las páginas',()=>{for(const p of pages){const h=renderPage(p);assert.match(h,/noindex,nofollow/);assert.ok(!/googletagmanager|google-analytics|G-W8L23NJLP6|antenistacerca/i.test(h));assert.equal((h.match(/<h1>/g)||[]).length,1);assert.ok(h.includes(site.tel));}});
test('cada municipio de la selección está en HTML sin JavaScript',()=>{for(const p of pages.filter(p=>p.type==='province'))for(const n of p.towns)assert.ok(townIndex(p).includes(esc(n)));});
test('enlaces locales conocidos se conservan',()=>{assert.match(townIndex(pages.find(p=>p.name==='Bizkaia')),/href="\/Antenas-Bizkaia\/bilbao.html"/);assert.match(townIndex(pages.find(p=>p.name==='Burgos')),/href="\/Antenas-Burgos\/lerma.html"/);});
test('generación determinista y libre de duplicados',()=>{for(const p of pages)assert.equal(renderPage(p),renderPage(p));assert.equal(new Set(pages.map(p=>p.path)).size,pages.length);});
test('modo de producción bloqueado',()=>{const old=process.env.SITE_MODE;process.env.SITE_MODE='production';try{assert.throws(()=>build(),/bloqueada/);}finally{if(old===undefined)delete process.env.SITE_MODE;else process.env.SITE_MODE=old;}});
test('no permite construir con el dominio vivo conectado',()=>{const old=process.env.URL;process.env.URL=site.domain;try{assert.throws(()=>build(),/dominio actual/);}finally{if(old===undefined)delete process.env.URL;else process.env.URL=old;}});
test('crea HTML real, 404 y cabeceras sin sitemap incompleto',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rapid-test-'));try{assert.equal(build(dir),13);assert.ok(fs.existsSync(path.join(dir,'404.html')));assert.match(fs.readFileSync(path.join(dir,'_headers'),'utf8'),/noindex/);assert.ok(!fs.existsSync(path.join(dir,'sitemap.xml')));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
