// Sección de servicio real, compartida por plantilla; no se inventan obras ni sedes.
const antennaBrands = ['Televés','Alcad','Ikusi','Fagor','Rover','EK','FTE Maximal','Fringe'];
const doorBrands = ['Fermax','Tegui','Golmar','Comelit','BTicino','Legrand','Fringe','Galak'];

function brandPills(items) {
  return `<div class="brand-pills">${items.map(name=>`<span>${name}</span>`).join('')}</div>`;
}

function trustAndBrands(page, esc) {
  const local = page.type === 'town' ? ` en ${esc(page.name)}` : '';
  return `<section class="trust section soft" id="experiencia"><div class="wrap"><div class="trust-grid"><div><span class="eyebrow">Criterios de trabajo</span><h2>Atención profesional para averías e instalaciones${local}</h2><div class="stars" aria-label="Cinco estrellas decorativas">★★★★★</div><p class="section-lead">Servicio orientado a viviendas, comunidades y negocios. Revisamos la instalación antes de proponer sustituciones y trabajamos tanto con equipos antiguos como con soluciones actuales.</p></div><div class="trust-points"><article><strong>Rapidez de atención</strong><p>Consulta por teléfono o WhatsApp indicando tu localidad.</p></article><article><strong>Experiencia real</strong><p>Instalaciones antiguas, renovaciones y equipos actuales.</p></article><article><strong>Diagnóstico antes de sustituir</strong><p>Primero localizamos el problema; después valoramos el cambio necesario.</p></article></div></div><div class="brands-block"><div><span class="eyebrow">Experiencia con equipos antiguos y actuales</span><h2>Marcas con las que trabajamos</h2><p class="section-lead">Equipos habituales en instalaciones de antena, amplificación, porteros automáticos y videoporteros.</p></div><div class="brand-group"><h3>Antenas y amplificación</h3>${brandPills(antennaBrands)}</div><div class="brand-group"><h3>Porteros y videoporteros</h3>${brandPills(doorBrands)}</div></div></div></section>`;
}

function mobileCoverage(page, phone, tel, esc) {
  const local = page.type === 'home' ? '' : ` en ${esc(page.name)}`;
  return `<section class="mobile-coverage section" id="cobertura-movil"><div class="wrap two-col"><div><span class="eyebrow">Vivienda individual</span><h2>Cobertura móvil 4G/5G${local}</h2><p class="section-lead">Estudio y mejora de cobertura para casas y viviendas individuales con mala recepción móvil o conexión de datos. Podemos valorar antenas exteriores para router 4G/5G y la distribución interior adecuada según la señal disponible.</p><p class="town-intro">Los repetidores de señal móvil para llamadas no se instalan de forma indiscriminada: su uso debe ajustarse a la normativa y a las condiciones del operador. Primero comprobamos qué solución encaja en la vivienda.</p></div><aside class="help-box"><h3>Consulta la cobertura de tu vivienda</h3><p>Indica localidad, operador, si el problema es de llamadas, datos o ambos y en qué zonas de la casa ocurre.</p><a class="text-call" href="${esc(tel)}">${esc(phone)}<span>Consultar cobertura móvil</span></a></aside></div></section>`;
}

export function doorphones(page, phone, tel, esc) {
  const heading = 'Porteros automáticos y videoporteros' + (page.type === 'home' ? '' : ` en ${page.name}`);
  const serviceLabel = page.type === 'home' ? 'Servicio técnico' : `Servicio en ${page.name} · ${phone}`;
  const base = `<section class="doorphones section" id="porteros-videoporteros"><div class="wrap"><div class="section-heading"><div><span class="eyebrow">${esc(serviceLabel)}</span><h2>${esc(heading)}</h2></div><a class="text-call" href="${esc(tel)}">${esc(phone)}<span>Consultar una reparación</span></a></div><p class="section-lead">Instalación, reparación, renovación y mantenimiento para viviendas y comunidades. Telefonillos, monitores y placas de calle: revisamos qué falla antes de proponer el cambio de un equipo.</p><div class="doorphone-work"><article><span class="work-number" aria-hidden="true">01</span><h3>Reparar una avería</h3><p>¿No llama, no se escucha o no abre la puerta? Indica si ocurre en una vivienda o en toda la comunidad. Revisamos llamada, audio, imagen y apertura según el sistema instalado.</p></article><article><span class="work-number" aria-hidden="true">02</span><h3>Instalar o renovar</h3><p>Instalación de porteros automáticos y videoporteros, cambio de telefonillos, monitores y placas. Antes de elegir un recambio, comprobamos la compatibilidad del cableado y del equipo existente.</p></article><article><span class="work-number" aria-hidden="true">03</span><h3>Mantener la instalación</h3><p>Consulta la revisión del acceso de tu comunidad: pulsadores, fuente de alimentación, conexiones y elementos de apertura. El alcance del mantenimiento se acuerda según la instalación.</p></article></div><p class="doorphone-note"><strong>Para preparar tu aviso:</strong> localidad, marca o modelo visible y qué función ha dejado de funcionar. No necesitas abrir ni desmontar el equipo.</p></div></section>`;
  const styles = `<style>.stars{font-size:30px;letter-spacing:4px;color:#d89a00;margin:8px 0 14px}.trust-grid{display:grid;grid-template-columns:1.05fr 1.4fr;gap:40px;align-items:start}.trust-points{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border:1px solid var(--line);background:#fff}.trust-points article{padding:22px}.trust-points article+article{border-left:1px solid var(--line)}.trust-points strong{display:block;font-size:16px}.trust-points p{margin:7px 0 0;color:var(--muted);font-size:13px}.brands-block{margin-top:34px;padding-top:30px;border-top:1px solid var(--line)}.brand-group{margin-top:20px}.brand-group h3{font-size:15px;margin:0 0 10px}.brand-pills{display:flex;flex-wrap:wrap;gap:8px}.brand-pills span{display:inline-flex;align-items:center;min-height:38px;padding:7px 12px;background:#fff;border:1px solid var(--line);font-weight:800;font-size:14px;border-radius:3px}.mobile-coverage{border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.mobile-coverage .text-call{display:block;margin-top:20px;color:var(--brand)}@media(max-width:760px){.trust-grid{grid-template-columns:1fr}.trust-points{grid-template-columns:1fr}.trust-points article+article{border-left:0;border-top:1px solid var(--line)}.brand-pills span{font-size:13px}}</style>`;
  return base + mobileCoverage(page, phone, tel, esc) + trustAndBrands(page, esc) + styles;
}
